---
- block:
    - set_fact:
        osts: "{{ vars[fs_name + '_osts'] | default(omit) }}"
        mgs: "{{ vars[fs_name + '_mgs'] | default(omit) }}"
        mdt: "{{ vars[fs_name + '_mdt'] | default(omit) }}"
        mgsnode: "{{ vars[fs_name + '_mgsnode'] }}"
        client_port: "{{ vars[fs_name + '_client_port'] }}"
    - set_fact:
        mgs_hostvars: "{{ hostvars[mgsnode] }}"
    - set_fact:
        fs_config_dir: "/etc/beegfs/{{ fs_name }}.d/"
        mgs_disk: "{{ mgs_hostvars['mgs'] }}"
    - set_fact:
        mgs_disk_info: "{{ beegfs_host_info[mgs_disk] }}"
    - set_fact:
        mgs_if_key: "ansible_{{ mgs_disk_info['if'] }}"
    - set_fact:
        mgs_port: "{{ mgs_disk_info['mgs_port'] }}"
        mgs_ip: "{{ hostvars[mgsnode][mgs_if_key]['ipv4']['address'] }}"
    - set_fact:
        mgs_dir: "/data/{{ fs_name }}/{{ mgs_disk }}/mgs"
  tags: ['never', 'create_mgs', 'create_mdt', 'stop_all']


- name: create template config
  block:
    - name: create fs config dir
      file:
        path: "{{ fs_config_dir }}"
        state: directory
    - name: copy default config
      shell: "cp /etc/beegfs/*.conf {{ fs_config_dir }}"
      args:
        creates: "{{ fs_config_dir }}beegfs-admon.conf"
  tags: ['never', 'create_mgs', 'create_mdt']


- name: create mgmtd service
  block:
    - name: make mgs dir
      file:
        path: "{{ mgs_dir }}"
        state: directory

    - name: BeeGFS mgmtd
      command: |
          /opt/beegfs/sbin/beegfs-setup-mgmtd \
          -p {{ mgs_dir }} -n \
          -S {{ fs_name }}-{{ ansible_host }}-{{ mgs_disk }} \
          -c {{fs_config_dir}}beegfs-mgmtd.conf
      register: command_result
      failed_when: "command_result.rc != 0 and ('ERROR: Storage directory is not empty.' not in command_result.stdout)"
      changed_when: "command_result.rc == 0"

    - name: set mgmtd port
      lineinfile:
        path: "{{ fs_config_dir }}beegfs-mgmtd.conf"
        regexp: '^{{ item }}.*'
        line: "{{ item }} = {{ mgs_port }}"
      loop:
        - "connMgmtdPortTCP"
        - "connMgmtdPortUDP"

    - name: set mgmtd ip
      lineinfile:
        path: "{{ fs_config_dir }}beegfs-mgmtd.conf"
        regexp: '^{{ item }}.*'
        line: "{{ item }} = {{ mgs_ip }}"
      loop:
        - "sysMgmtdHost"

    - name: set mgmtd logfile
      lineinfile:
        path: "{{ fs_config_dir }}beegfs-mgmtd.conf"
        regexp: '^{{ item }}.*'
        line: "{{ item }} = /var/log/{{ fs_name }}-beegfs-mgmtd.log"
      loop:
        - "logStdFile"

    - name: write out interfaces file
      copy:
        content: "{{ mgs_disk_info['if'] }}"
        dest: "{{ fs_config_dir }}connInterfacesFile{{ mgs_disk_info['if'] }}"

    - name: set conInterfacesFile in config
      lineinfile:
        path: "{{ fs_config_dir }}beegfs-mgmtd.conf"
        regexp: '^{{ item }}.*'
        line: "{{ item }} = {{ fs_config_dir }}connInterfacesFile{{ mgs_disk_info['if'] }}"
      loop:
        - "connInterfacesFile"

    - name: Start mgmtd
      systemd:
        state: started
        name: "beegfs-mgmtd@{{ fs_name }}.service"

  when:
    - mgs is defined
  tags: ['never', 'create_mgs']


- name: create meta service
  block:
    - set_fact:
        mdt_dir: "/data/{{ fs_name }}/{{ mdt }}/mdt"
        mdt_disk_info: "{{ beegfs_host_info[mdt] }}"
    - set_fact:
        mdt_port: "{{ mdt_disk_info['mdt_port'] }}"
        mdt_index: 1
        mdt_ip: hostvars[inventory_hostname]['ansible_{{ mdt_disk_info["if"] }}']['ipv4']['address']

    - name: Configure BeeGFS meta
      command: |
          /opt/beegfs/sbin/beegfs-setup-meta \
          -p {{ mdt_dir }} \
          -s {{ mdt_index }} \
          -m {{ mgs_ip }} \
          -S {{ fs_name }}-{{ ansible_host }}-{{ mdt }} \
          -c {{fs_config_dir}}beegfs-meta.conf
      register: command_result
      failed_when: "command_result.rc != 0 and ('ERROR: Storage directory is not empty.' not in command_result.stdout)"
      changed_when: "command_result.rc == 0"

    - name: set meta port
      lineinfile:
        path: "{{ fs_config_dir }}beegfs-meta.conf"
        regexp: '^{{ item }}.*'
        line: "{{ item }} = {{ mdt_port }}"
      loop:
        - "connMetaPortTCP"
        - "connMetaPortUDP"

    - name: set mgmtd port for meta
      lineinfile:
        path: "{{ fs_config_dir }}beegfs-meta.conf"
        regexp: '^{{ item }}.*'
        line: "{{ item }} = {{ mgs_port }}"
      loop:
        - "connMgmtdPortTCP"
        - "connMgmtdPortUDP"

    - name: set mgmtd logfile
      lineinfile:
        path: "{{ fs_config_dir }}beegfs-meta.conf"
        regexp: '^{{ item }}.*'
        line: "{{ item }} = /var/log/{{ fs_name }}-beegfs-meta.log"
      loop:
        - "logStdFile"

    - name: write out interfaces file
      copy:
        content: "{{ mdt_disk_info['if'] }}"
        dest: "{{ fs_config_dir }}connInterfacesFile{{ mdt_disk_info['if'] }}"

    - name: set conInterfacesFile in config
      lineinfile:
        path: "{{ fs_config_dir }}beegfs-meta.conf"
        regexp: '^{{ item }}.*'
        line: "{{ item }} = {{ fs_config_dir }}connInterfacesFile{{ mdt_disk_info['if'] }}"
      loop:
        - "connInterfacesFile"

    - name: Start services meta
      systemd:
        state: started
        name: "beegfs-meta@{{ fs_name }}.service"
  when:
    - mdt is defined
  tags: [ 'never', 'create_mdt']
