---
- set_fact:
    osts: "{{ vars[fs_name + '_osts'] | default(omit) }}"
    mgs: "{{ vars[fs_name + '_mgs'] | default(omit) }}"
    mdt: "{{ vars[fs_name + '_mdt'] | default(omit) }}"
    mgsnode: "{{ vars[fs_name + '_mgsnode'] }}"
    client_port: "{{ vars[fs_name + '_client_port'] }}"
  tags: ['never', 'format', 'mount', 'unmount', 'stop_all']
- set_fact:
    mdt_disk: "{{ mdt | default([]) }}"
    mgs_disk: "{{ mgs | default([]) }}"
    osts: "{{ osts | default({}) }}"
  tags: ['never', 'format', 'mount', 'unmount', 'stop_all']
- set_fact:
    all_disks: "{{ osts.keys() | union([mdt_disk]) | union([mgs_disk]) | flatten | unique | list }}"
  tags: ['never', 'format', 'mount', 'unmount', 'stop_all']

- name: Format disks
  command: "mkfs.ext4 -E lazy_itable_init=0,lazy_journal_init=0,discard -b 4096 -i 8192 -I 512 -Odir_index,filetype,^has_journal /dev/{{ item }}"
  loop: "{{ all_disks }}"
  tags: ['never', 'format']

- name: Setup disks
  block:

    - name: Create mount point dir
      file:
        path: /data/{{ fs_name }}/{{ item }}
        state: directory
        recurse: yes
      loop: "{{ all_disks }}"

    - name: Mount EXT4 OSTs
      command: mount -onoatime,nodiratime,nobarrier,user_xattr,discard /dev/{{ item }} /data/{{ fs_name }}/{{ item }}
      register: command_result
      failed_when: "command_result.rc != 0 and ('is already mounted' not in command_result.stderr)"
      changed_when: "command_result.rc == 0"
      loop: "{{ all_disks }}"

  tags: ['never', 'mount']
