---
- include: repo.yaml
- include: client-build-ops.yaml
- include: format-mount.yaml
- include: create-mgs-mdt.yaml
- include: create-ost.yaml
- include: client.yaml
- include: stop-all.yaml
- include: unmount.yaml
